[package]
title = "Meta Cloud Explorer (Azure)"
description="An Omniverse scene authoring tool to help visualize your Azure Infrastructure in your own private Metaverse!"
version = "2022.1.3"
category = "Browsers"
authors = ["CloudArchitect.live"]
preview_image = "data/resources/azurescaled.png"
icon = "data/resources/meta_cloud_explorer.png"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
repository = "https://github.com/USDSync/MetaCloudExplorer"

# Keywords for the extension
keywords = ["Azure", "CloudArchitect.live", "Meta Cloud Explorer (Azure)", "scene authoring tools"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.filepicker" = {}
"omni.kit.window.file_importer" = {}

[python.pipapi]
requirements = [
     "pandas",
     "numpy",
     "azure-mgmt-resource",
     "azure-identity",
     "typing-extensions"
]

# Main python module this extension provides, it will be publicly available as "import meta.cloud.explorer.azure".
[[python.module]]
name = "meta.cloud.explorer.azure"
